### PR TITLE
[requires.io] dependency update on master branch

### PR DESCRIPTION
**Pull request by Lukasa**

### CODE REVIEW

**Comment by rbtcollins** [comment]
wow appveyor is slow... 4 hours queued ? what tests are we running there?

**Comment by Lukasa** [comment]
@rbtcollins The standard tests, same as we run on Travis. The problem is that appveyor only gives us one parallel build, and the build matrix is large. Additionally, it was getting blocked behind work I am doing on Windows wheels.

Sadly, build times on this project are pretty much always going to be bad unless I can find a way to get something better than appveyor.

**Comment by rbtcollins** [comment]
What does appveyor add over travis?

**Comment by Lukasa** [comment]
@rbtcollins Windows. =)

**Comment by rbtcollins** [comment]
Given the IO free nature of hyper-h2, I'm curious what we learn from
Windows tests. Perhaps we could run a very limited matrix there - e.g.
just the wheel and basic 'its all importable' or something?

**Comment by Lukasa** [comment]
This isn't the hyper-h2 repo, it's the certitude repo, which is a binary module. ;)

**Pull request merged**
